apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-deploy
    labels: mongo-deploy
        name: mongo-deploy
        app: microservices-libreria
    spec:
        replicas: 1
        selector:
            matchlabels:
                app: microservices-librerias
                name: mongo-pod
            template:
              metadata:
                name: mongo-pod
                labels:
                    app: microservices-librerias
                    name: mongo-pod
            spec:
                containers:
                - name: mongo
                  image: mongo:4.12.12
                  command:
                    - /bin/bash
                    - -c
                  env:
                    - name: MONGO_INITDB_ROOT_USERNAME
                      value: "vaxidrez"
                      name: MONGO_INITDB_ROOT_PASSWORD
                      value: "$VaxiDrez2025"
                  ports:
                    - containerPort: 27017  
                
        
        